# 1. NumPy 

O Numpy é uma biblioteca Python usada principalmente para realizar cálculos em arrays multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:
* Modelos de Machine Learning
* Processamento de Imagem e Computação Gráfica
* Tarefas matemáticas 


NumPy pode ser importado no ambiente com o comando ```import numpy```,
como no exemplo abaixo:


In [ ]:
import numpy as np 
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

## 1.1 Documentação:

*  https://numpy.org/doc/
* Ajuda interativa:

In [ ]:
np.array?

* Procurando por algo:

In [ ]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.ma.MaskedArray.__new__
    Create a 

In [ ]:
np.con*?



## 1.2 Criação de *arrays*

Um array NumPy é um coleção multidimensional e uniforme de elementos, isto é, todos os elementos ocupam o mesmo número de bytes em
memória.

Arrays podem ser facilmente criados com a função *array*, que recebe como
argumento uma lista contendo os dados que deverão ser armazenados.
O número de dimensões de um array pode ser obtido pelo atributo ```ndim```
enquanto que as dimensões em si ficam armazenadas no atributo ```shape```:

In [ ]:
a.ndim

1

In [ ]:
a.shape

(4,)

In [ ]:
len(a)

4

A lista com os dados pode conter uma estrutura que permita ao método
array inferir as dimensões pretendidas. Por exemplo, uma matriz 2D pode
ser inicializada a partir de uma **lista de listas**:

In [ ]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
c = np.array([[[1], [2]], [[3], [4]]])

In [ ]:
c.shape

(2, 2, 1)

## 1.2.1 Utilitários para criação de *arrays*

Para criar um *array* contendo uma sequência com ```n``` elementos de ```0``` a ```n-1```,
podemos utilizar a função ```arange```: 

```python
np.arange(numero_elementos)
```

Também podemos defirnir os elementos inicial e final e um passo entre os elementos sucessivos:

```python
np.arange(inicio, fim(exclusive), passo)
```

In [ ]:
a = np.arange(10) # elementos [0, 1, ..., n-1] último exclusive
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1, 9, 2) # inicio, fim (exclusive), passo
b

array([1, 3, 5, 7])

Para uma sequência de
números reais, igualmente espaçada dentro de um intervalo, pode-se utilizar o ```linspace```:

> Sintaxe
```python
linspace(inicio, fim numero-de-pontos)
```

Para criarmos um *array* com ```n``` números reais igualmente espaçados no intervalo ```[0,1]```, utiliza-se ```zeros```, ```ones```, ```identity```.
Para produzir matrizes de dimensões variadas
com um valor fixo, podemos utilizar as funções ```zeros``` e ```ones```, informando
as dimensões desejadas na forma de uma tupla como argumento:


In [ ]:
a = np.ones((3, 3)) # lembrando que (3, 3) é uma tupla
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

Matrizes identidade são particularmente importantes em computação envolvendo álgebra linear. A função ```identity``` produz uma matriz quadrada
do tamanho desejado, com todos os elementos em sua diagonal principal
apresentando o valor 1, zero para todos os demais:

In [ ]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

*Arrays* aleatórios podem ser produzidos utilizando-se o submódulo ```random``` do NumPy.

Valores obtidos de uma distribuição uniforme no intervalo ```[0,1]``` são
produzidos com ```rand```:

In [ ]:
a = np.random.rand(4) # uniform in [0, 1]
a

array([0.50755507, 0.0211933 , 0.43352176, 0.44631306])

Outra opção é utilizar uma distribuição Gaussiana através da função
```randn```:

In [ ]:
A = np.random.randn(4)
A

array([ 0.65034618, -0.51433646,  0.53942869,  1.52676162])

## 1.3 Tipos de dados

Diferente de listas, que podem armazenar elementos de tipos diferentes,
*arrays* devem conter elementos de mesmo tipo, como especificado em
```dtype```. 

In [ ]:
v = np.array([1,2,3])
v.dtype

dtype('int64')

Acima, vemos que o tipo padrão para inteiros adotado pelo sistema em
uso no exemplo utiliza 64 bits. Similarmente, vemos que o tipo padrão para
ponto flutuante também se baseia em 64 bits:

In [ ]:
v = np.array([1., 2., 3.])
v.dtype

dtype('float64')

Alternativamente, podemos especificar exatamente o tipo desejado, dentre
os disponíveis na NumPy. O exemplo abaixo cria um array com elementos
em ponto flutuante, apesar do argumento de entrada consistir
em uma lista de inteiros: 

In [ ]:
v = np.array([1,2,3], dtype=float)
v

array([1., 2., 3.])

In [ ]:
v.dtype

dtype('float64')

Outros tipos:

In [ ]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

In [ ]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

In [ ]:
f = np.array(['Oi', 'Ola', 'Hi'])
f.dtype     # <--- strings contendo no máximo 7 letras 

dtype('<U3')

## 1.4 Indexação e Fatiamento

Os elementos de um array podem ser acessados e atribuídos da mesma forma que as outras sequências em Python:

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0], a[2], a[-1]

(0, 2, 9)

Também podemos inverter um array da mesma forma que uma lista:

In [ ]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Para arrays multidimensionais, os índices são tuplas de inteiros:

In [ ]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [ ]:
a[1, 1]

1

In [ ]:
a[2, 1] = 10 # terceira linha, segunda coluna
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [ ]:
a[1]

array([0, 1, 0])

* Em um array 2D, a primeira dimensão corresponde as **linhas** e a segunda, **colunas**
* Para um array multidimensional ```a```, ```a[0]``` é interpretado pegando-se todos os elementos de uma dimensão não especificada.

Os arrays também podem ser fatiados:

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:9:3]  # [inicio:fim:passo]

array([2, 5, 8])

Note que, assim como em qualquer sequência do Python, o último índica não é incluído:

In [ ]:
a[:4]   

array([0, 1, 2, 3])

Nenhum dos três componentes para o corte são necessários: por padrão, o início é 0, o final é o último e o incremento é 1:

In [ ]:
a[1:3]

array([1, 2])

In [ ]:
a[::2]

array([0, 2, 4, 6, 8])

In [ ]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

Veja uma ilustração sobre indexação e fatiamento de arrays no Numpy:

<img src="figures/indexacao-array.png" />

## 1.5 Cópias e Visualizações 

Uma operação de corte cria uma visualização do array original, a qual é apenas uma forma de se acessar dos dados da array. Assim, a matriz original não é copiada na memória.

Quando modifica-se a visualização, a array original também é modificada:

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
b[0] = 12
b

array([12,  2,  4,  6,  8])

In [ ]:
a

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)
b = a[::2].copy()  # forçar a cópia
b[0] = 12
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Esse comportamento permite economizar memória e tempos.

## 1.5.1 Indexação sofisticada

Arrays NumPy podem ser trabalhadas com cortes, mas também com arrays booleanas ou de inteiros (máscaras). Esse método é conhecido como fancy indexing (indexação sofisticada). Ele cria copias e não visualizações.

### Usando máscaras booleanas

In [ ]:
np.random.seed(3)
a = np.random.randint(0, 21, 15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [ ]:
(a % 3 == 0)

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False])

In [ ]:
mask = (a % 3 == 0)

extract_from_a = a[mask] # or,  a[a%3==0]
extract_from_a  

array([ 3,  0,  9,  6,  0, 12])

Indexar com uma máscara pode ser muito útil para atribuir um novo valor para uma subarray:

In [ ]:
a[a % 3 == 0] = -1
a

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1,  7, 14])

### Usando um array de inteiros

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Podemos indexar com um array de inteiro, onde o mesmo índice é repetido diversas vezes:

In [ ]:
a[[2, 3, 2, 4, 2]]  # note: [2, 3, 2, 4, 2] é uma lista do Python

array([2, 3, 2, 4, 2])

Novos valores podem ser atribuídos da seguinte maneira:

In [ ]:
a[[9, 7]] = -10
a

array([  0,   1,   2,   3,   4,   5,   6, -10,   8, -10])

Quando um novo array é criado por indexação de um array de inteiros, o novo array possui a mesma forma do array de inteiros:

In [ ]:
a = np.arange(10)
idx = np.array([[3,4], [9,7]])
idx.shape

(2, 2)

In [ ]:
a[idx]

array([[3, 4],
       [9, 7]])

A imagem ilustra as diversas aplicações da indexação sofisticada:

<img src="figures/fancy-indexacao-array.png" />

## 1.6 Manipulando arrays

### Operações entre os elementos:

In [ ]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])
sum = a + b # Soma
difference = a - b # Subtração
product = a * b # Multiplicação
quotient = a / b # Divisão
print('Sum = \n', + sum)
print('\n')
print('Difference = \n', + difference)
print('\n')
print('Product = \n', + product)
print('\n')
print('Quotient = \n', + quotient)

Sum = 
 [[ 6.  8.]
 [10. 12.]]


Difference = 
 [[-4. -4.]
 [-4. -4.]]


Product = 
 [[ 5. 12.]
 [21. 32.]]


Quotient = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Operações entre arrays, elemento por elemento:

In [ ]:
A = np.ones((3,3))
B = 2 * np.ones((3,3))
print(A)
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
A + B

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

**Importante** : multiplicação de *arrays* não equivale à multiplicação de matrizes. A multiplicação de matrizes, como definida em álgebra, é obtida com a função ```dot```:

In [ ]:
np.dot(A,B)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

### Transposição:

In [ ]:
A =	np.arange(12).reshape(3,4)

In [ ]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Comparações:

In [ ]:
u =	np.random.rand(5)
u

array([0.64914405, 0.27848728, 0.6762549 , 0.59086282, 0.02398188])

In [ ]:
v = np.random.rand(5)
v

array([0.55885409, 0.25925245, 0.4151012 , 0.28352508, 0.69313792])

In [ ]:
u > v

array([ True,  True,  True,  True, False])

In [ ]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### 1.3.2 Reduções básicas

### Soma

In [ ]:
x = np.array([1, 2, 3, 4])
x.sum()

10

Somando ao longo de linhas e colunas:

<img src="figures/soma-array.png" />

In [ ]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum(axis=0)     # colunas

array([3, 3])

In [ ]:
x[:, 0].sum(), x[:, 1].sum()

(3, 3)

In [ ]:
x.sum(axis=1) # linhas

array([2, 4])

### Extremos


In [ ]:
x = np.array([1, 3, 2])
x.min()

1

In [ ]:
x.max()

3

In [ ]:
x.argmin()    # índice do valor mínimo

0

In [ ]:
x.argmax()    # índice do valor máximo

1

### Estatística

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

In [ ]:
x.mean()

1.75

In [ ]:
np.median(x)

1.5

In [ ]:
np.median(y, axis = -1)   # último eixo

array([2., 5.])

In [ ]:
x.std()   # desvio padrão

0.82915619758885

### Manipulando forma - Achatar

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T.flatten()

array([1, 4, 2, 5, 3, 6])

### Manipulando forma - Reformatar

In [ ]:
a.shape

(2, 3)

In [ ]:
b = a.flatten()
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

Resumo: 

### Criação de arrays

```python
np.array([1,2,3])           # Array 1D
np.array([(1,2,3),(4,5,6)]) # Array 2D
np.zeros(5)                 # Arrays 1D de comprimento 5 com todos os valores = 0
np.ones((5, 3))             # Array de tamanho 5x3 com todos os valores = 1
np.eye(5)                   # Array de tamanho 5x5 com valor 1 na diagonal e 0 no restante (matriy identidade
np.linspace(0,100,6)        # Array com 6 elementos com valores divididos de forma igual entre 0 e 100
np.arange(0,10,3)           # Array com valores de 0 até 10 (não incluído) em passos de 3 (por exemplo [0,3,6,9])
np.full((2,3),8)            # Array de tamanho 2x3 com todos os valores = 8
np.random.rand(4,5)         # Array de tamanho 4x5 com valores aleatórios entre 0–1
np.random.rand(6,7)*100     # Array de tamanho 6x7 com valores aleatórios entre 0–100
np.random.randint(5,size=(2,3)) # Array de tamanho 2x3 com valores aleatórios inteiros entre 0–4
```

### Propriedades

```python
arr.size          # retorna o número de elementos em arr
arr.shape         # retorna a dimensão de arr (linhas,colunas)
arr.dtype         # retorna o tipo dos dados em arr
arr.astype(dtype) # converte o tipo dos elementos de arr para dtype
arr.tolist()      # converte o arr em uma lista
np.info(np.eye)   # ver a documentação de np.eye

```

### Copiando/ordenando/reformatando

```python
np.copy(arr)        # copia arr para um novo endereço de memória
arr.view(dtype)     # cria uma visualização dos elementos de arr com o tipo dtype
arr.sort()          # ordena arr
arr.sort(axis=0)    # ordena um exico específico de arr
two_d_arr.flatten() # achata um array 2D em 1D
arr.T               # transposta de arr (linhas viram colunas e vice-versa)
arr.reshape(3,4)    # reformata arr para 3 linhas e 4 colunas, sem alterar os dados
arr.resize((5,6))   # altera a forma de arr para 5x6 e preenche os novos valores com 0
```

### Adicionando/removendo elementos

```python
np.append(arr,valores)     # adiciona valores ao final de arr
np.insert(arr,2,valores)   # insere valores em arr antes do índice 2
np.delete(arr,3,axis=0)    # deleta linha de índice 3 de arr
np.delete(arr,4,axis=1)    # deleta coluna de índice 4 de arr
```

### Combinando/separando

```python
np.concatenate((arr1,arr2),axis=0)   # adiciona arr2 como linhas ao final de arr1
np.concatenate((arr1,arr2),axis=1)   # adiciona arr2 como colunas ao final de arr1
np.split(arr,3)                      # separa arr em 3 subarrays
np.hsplit(arr,5)                     # separa arr horizontalmente no índice 5
```

### Indexando/fatiando

```python
arr[5]              # retorna o elemento de índica [5]
arr[2,5]            # retorna o elemento do array 2D de índices [2][5]
arr[1]=4            # atribui ao elemento do array de índice 1 o valor 4
arr[1,3]=10         # atribui ao elemento do array de índice [1][3] o valor 10
arr[0:3]            # retorna os elementos nos índices 0,1,2 (se o arr for 2D: retorna as colunas 0,1,2)
arr[0:3,4]          # retorna os elementos das linhas 0,1,2 na coluna 4
arr[:2]             # retorna os elementos nos índices 0,1 (se o arr for 2D: retorna colunas 0,1)
arr[:,1]            # retorna os elementos de índice 1 para todas as linhas 
arr<5               # retorna um array com valores booleanos
(arr1<3) & (arr2>5) # retorna um array com valores booleanos
~arr                # inverte um array booleano
arr[arr<5]          # retorna um array com elementos menores que 5
```

### Matemática escalar e vetorial

```python
np.add(arr,1)              # adiciona 1 em cada elemento do array
np.subtract(arr,2)         # subtrai 2 em cada elemento do array
np.multiply(arr,3)         # multiplica cada elemento do array por 3
np.divide(arr,4)           # divide cada elemento do array por 4 (retorna np.nan se a divisão for por zero)
np.power(arr,5)            # eleva cada elemento do array a quinta potência
np.add(arr1,arr2).         # adiciona elemento a elemento arr1 de arr2
np.subtract(arr1,arr2)     # subtrai elemento a elemento de arr2 de arr1
np.multiply(arr1,arr2)     # multiplica elemento a elemento arr1 por arr2
np.divide(arr1,arr2)       # divide elemento a elemento arr1 de arr2
np.power(arr1,arr2)        # eleva cada elemento de arr1 a potênica de cada elemento de  arr2 
np.array_equal(arr1,arr2)  # retorna True se os arrays possuem os mesmo elementos e mesma forma
np.sqrt(arr)               # retorna a raíz quadrada de cada elemento do array
np.sin(arr)                # retorna seno de cada elemento do array
np.log(arr)                # retorna log de cada elemento do array
np.abs(arr)                # retorna valor absoluto de cada elemento do array
np.ceil(arr)               # retorna o valor inteiro mais próximo para cima de cada elemento do array
np.floor(arr)              # retorna o valor inteiro mais próximo para baixo de cada elemento do array
np.round(arr)              # retorna o valor inteiro mais próximo de cada elemento do array
```

### Estatística

```python
np.mean(arr,axis=0)  # retorna o valor médio ao longo de um eixo específico
arr.sum()            # retorna a soma do array
arr.min()            # retorna o valor mínimo do array
arr.max(axis=0)      # retorna o valor máximo em um eixo específico
np.var(arr)          # retorna a variância do array
np.std(arr,axis=1)   # retorna o desvio padrão em um eixo específico
arr.corrcoef()       # retorna o coeficiente de correlação do array
```

## Referências:

https://scipy-lectures.org/intro/numpy/